name: Fix All

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  fix-all:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'trustwallet' && github.event.repository.fork == false

    steps:
      - name: Checkout (trustwallet repo, secret token)
        uses: actions/checkout@v3
        with:
          # Use trust-ci fine-grained PAT to checkout and later commit the code
          # Do not use for forked repos
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Run fix
        run: make fix

      - name: Show fix result (diff)
        run: |
          git status
          git diff

      - name: Run check
        run: make check

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_user_name: trust-ci
          commit_user_email: "117647528+trust-ci@users.noreply.github.com"
          commit_message: Auto fix all (sanity and consistency)
