name: Periodic External Update
on:
  schedule:
    # Run twice per day (at 1:00UTC/6pmPST, 13:00UTC/6amPST)
    - cron:  '0 1,13 * * *'
  workflow_dispatch:
jobs:
  periodic-auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
        id: go

      - name: Run update auto
        run: make update-auto

      - name: Show update result (diff)
        if: success()
        run: |
          git status
          git diff

      - name: Run check
        run: make check

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: External Updates
          commit_user_name: trust-ci
          commit_user_email: "117647528+trust-ci@users.noreply.github.com"
